# Generated by Django 4.1 on 2021-08-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notetype",
            name="category",
            field=models.CharField(max_length=25),
        ),
    ]
