# Generated by Django 4.1 on 2023-06-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notetype",
            name="creator_id",
            field=models.IntegerField(default=0),
        ),
    ]
