# Generated by Django 4.1 on 2023-04-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="short_desciption",
            new_name="short_description",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="tasks_scheduler",
            new_name="task_scheduler",
        ),
    ]
