# Generated by Django 4.1 on 2023-08-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="short_description",
            field=models.CharField(max_length=30),
        ),
    ]
