# Generated by Django 4.1 on 2023-06-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_priority",
        ),
        migrations.AddField(
            model_name="task",
            name="task_priority",
            field=models.CharField(
                choices=[("LOW", "low"), ("MEDIUM", "medium"), ("HIGH", "high")],
                default="low",
                max_length=6,
            ),
        ),
    ]
