# Generated by Django 4.1 on 2023-04-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_rename_short_desciption_task_short_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="short_description",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_description",
            field=models.TextField(max_length=200),
        ),
    ]
