# Generated by Django 4.1 on 2023-07-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_priority",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                default="LOW",
                max_length=6,
            ),
        ),
    ]
