# Generated by Django 4.1 on 2023-04-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_short_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-due_date", "-due_time"]},
        ),
        migrations.AddField(
            model_name="task",
            name="is_priority",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="task_done",
            field=models.BooleanField(default=False),
        ),
    ]
