# Generated by Django 4.1 on 2023-04-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_options_task_is_priority_task_task_done"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="task_done",
            new_name="task_completed",
        ),
    ]
